name: terraform CI

on:
    push:
        branches: [main]
        paths: ["**.tf"]
    pull_request:
        branches: [main]
        paths: ["**.tf"]

jobs:
    fmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v3
            - run: terraform fmt -check -recursive 
        
    validate:
        runs-on: ubuntu-latest
        needs: fmt
        strategy:
            matrix:
                environment: [dev,prod]   #add prod later to the list
        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v3
            - name: Init without the backend
              run: terraform init -backend=false
              working-directory: environments/${{matrix.environment }}
            - name: validate
              run: terraform validate
              working-directory: environments/${{matrix.environment }}